# Atelier replay. Rebuild with: atelier replay <this-file>
format = 1
renderer = 1
name = "sc-opus-slash"
canvas = [32, 32]
frames = [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
palette = ["#2e225c", "#5c4ec8", "#8ccdfa", "#e8f4ff", "#ffffff", "#ffe296"]

[[layers]]
name = "trail"

[[layers.cels]]
frames = [0]
origin = [1, 10]
legend = { 1 = "#2e225c", 2 = "#5c4ec8" }
grid = '''
1.
..
.2
.2
'''

[[layers.cels]]
frames = [1]
origin = [1, 10]
legend = { 1 = "#2e225c", 2 = "#5c4ec8", 3 = "#8ccdfa" }
grid = '''
1...
22..
.2..
.2..
.22.
..3.
....
...3
'''

[[layers.cels]]
frames = [2]
origin = [1, 12]
legend = { 1 = "#2e225c", 2 = "#5c4ec8", 3 = "#8ccdfa", 4 = "#e8f4ff" }
grid = '''
.1.......
222......
.22......
.222.....
..23.....
..333....
...333...
....333..
.....333.
......343
.......3.
'''

[[layers.cels]]
frames = [3]
origin = [1, 12]
legend = { 1 = "#5c4ec8", 2 = "#2e225c", 3 = "#8ccdfa", 4 = "#e8f4ff", 5 = "#ffffff" }
grid = '''
.1..........
121.........
.11.........
.111........
..11........
..113.......
...333......
....333.....
.....333....
......333...
.......343..
........343.
.........343
..........35
'''

[[layers.cels]]
frames = [4]
origin = [2, 14]
legend = { 1 = "#5c4ec8", 2 = "#2e225c", 3 = "#e8f4ff", 4 = "#8ccdfa", 5 = "#ffffff" }
grid = '''
.1............
121...........
.11...........
.11...........
.111..........
..111.........
...111........
....111.......
.....131......
......1344....
.......43344..
.......4433344
.........44335
...........455
'''

[[layers.cels]]
frames = [5]
origin = [3, 16]
legend = { 1 = "#5c4ec8", 2 = "#2e225c", 3 = "#8ccdfa", 4 = "#e8f4ff" }
grid = '''
.1..................
121.................
.111................
..111...............
...111..............
....1333............
.....3333...........
.....33333..........
......33333.........
.......33343........
........344443......
.........344444.....
...........34444444.
..............444444
................444.
'''

[[layers.cels]]
frames = [6]
origin = [6, 19]
legend = { 1 = "#5c4ec8", 2 = "#2e225c", 3 = "#8ccdfa", 4 = "#e8f4ff" }
grid = '''
.1..............
121.............
.111............
..113...........
...333..........
....3333........
......333.......
.......3333.....
.........343....
..........344...
.............44.
..............44
'''

[[layers.cels]]
frames = [7]
origin = [11, 24]
legend = { 1 = "#2e225c", 2 = "#5c4ec8", 3 = "#8ccdfa" }
grid = '''
1..........
.22........
...3.......
....33.....
......33...
.......333.
.........33
'''

[[layers.cels]]
frames = [8]
origin = [15, 27]
legend = { 1 = "#2e225c", 2 = "#5c4ec8" }
grid = '''
11.....
.11....
....2..
......2
'''

[[layers]]
name = "flash"

[[layers.cels]]
frames = [5]
origin = [20, 25]
legend = { 1 = "#ffe296", 2 = "#ffffff" }
grid = '''
..1....
..1....
..1....
.22....
2222111
..2211.
..11...
'''

[[layers.cels]]
frames = [6]
origin = [22, 29]
legend = { 1 = "#ffffff", 2 = "#ffe296" }
grid = '''
1.2.
2222
'''
