//! Editable pixel-atlas metadata and static, unhinted TrueType export.

use std::collections::HashSet;
use std::path::Path;

use image::RgbaImage;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use write_fonts::read::tables::glyf::CurvePoint;
use write_fonts::tables::glyf::{Contour, Glyph, SimpleGlyph};

use super::{DocMeta, Document};

mod encode;
#[cfg(test)]
mod tests;

/// Maximum editable glyph count, including space and the missing glyph.
pub const MAX_FONT_GLYPHS: usize = 4096;
/// Maximum Unicode mappings; also bounds the BMP cmap's 16-bit offsets.
pub const MAX_FONT_MAPPINGS: usize = 4096;
/// Maximum aggregate source pixels scanned by one font export.
pub const MAX_FONT_PIXELS: u64 = 16 * 1024 * 1024;
/// Maximum aggregate outline points generated by one font export.
pub const MAX_FONT_POINTS: usize = 1024 * 1024;
// Each horizontal run needs four points. TrueType point indices are u16.
const MAX_GLYPH_RUNS: usize = u16::MAX as usize / 4;

const fn default_units_per_em() -> u16 {
    1024
}
const fn default_units_per_pixel() -> u16 {
    64
}

/// One editable glyph. Coordinates and advances are in source pixels.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct FontGlyph {
    pub name: String,
    /// Unicode scalar values; multiple codepoints may share this glyph.
    pub codepoints: Vec<u32>,
    /// Atlas [x, y, width, height], or null for a glyph with no outline.
    pub rect: Option<[u32; 4]>,
    /// Horizontal advance in pixels, including any trailing spacing.
    pub advance: u32,
    /// Horizontal position of the rectangle's left edge relative to the pen.
    #[serde(default)]
    pub bearing_x: i32,
}

/// Static font configuration persisted with a pixel-art document.
#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct FontMeta {
    pub family: String,
    /// Render this atlas frame using the document's visible layers.
    #[serde(default)]
    pub frame: usize,
    /// Baseline measured down from each glyph rectangle's top edge, in pixels.
    pub baseline: u32,
    /// Distance above the baseline in pixels (positive).
    pub ascent: u32,
    /// Distance below the baseline in pixels (positive or zero).
    pub descent: u32,
    #[serde(default)]
    pub line_gap: u32,
    #[serde(default = "default_units_per_em")]
    #[schemars(range(min = 16, max = 16384))]
    pub units_per_em: u16,
    /// Integer font units per source pixel; no resampling is performed.
    #[serde(default = "default_units_per_pixel")]
    #[schemars(range(min = 1, max = 32767))]
    pub units_per_pixel: u16,
    /// Index into glyphs. Exported as glyph ID zero (.notdef).
    pub missing_glyph: usize,
    /// Index into glyphs. Must have no rectangle and include U+0020.
    pub space_glyph: usize,
    pub glyphs: Vec<FontGlyph>,
}

fn scaled(value: i64, units: u16, label: &str) -> Result<i16, String> {
    i16::try_from(value * i64::from(units))
        .map_err(|_| format!("font {label} exceeds the signed 16-bit TrueType range"))
}

fn validate_name(value: &str, label: &str) -> Result<(), String> {
    if value.trim().is_empty() || value.len() > 128 || value.chars().any(char::is_control) {
        return Err(format!(
            "font {label} must be 1..=128 UTF-8 bytes with no control characters"
        ));
    }
    Ok(())
}

impl FontMeta {
    pub(super) fn validate(&self, doc: &DocMeta) -> Result<(), String> {
        validate_name(&self.family, "family")?;
        if self.frame >= doc.frames.len() {
            return Err(format!("font atlas frame {} does not exist", self.frame));
        }
        if !(16..=16384).contains(&self.units_per_em) || self.units_per_pixel == 0 {
            return Err(
                "font units_per_em must be 16..=16384 and units_per_pixel must be positive".into(),
            );
        }
        if self.ascent == 0 || self.baseline > self.ascent {
            return Err("font ascent must be positive and cover the baseline".into());
        }
        scaled(i64::from(self.ascent), self.units_per_pixel, "ascent")?;
        scaled(i64::from(self.descent), self.units_per_pixel, "descent")?;
        scaled(i64::from(self.line_gap), self.units_per_pixel, "line gap")?;
        if self.glyphs.is_empty() || self.glyphs.len() > MAX_FONT_GLYPHS {
            return Err(format!("font must contain 1..={MAX_FONT_GLYPHS} glyphs"));
        }
        if self.missing_glyph >= self.glyphs.len()
            || self.space_glyph >= self.glyphs.len()
            || self.missing_glyph == self.space_glyph
        {
            return Err(
                "font missing_glyph and space_glyph must identify distinct existing glyphs".into(),
            );
        }
        if self.glyphs[self.missing_glyph].rect.is_none() {
            return Err("font missing-character glyph needs an atlas rectangle".into());
        }
        let space = &self.glyphs[self.space_glyph];
        if space.rect.is_some() || !space.codepoints.contains(&32) {
            return Err("font space glyph must have rect=null and map U+0020".into());
        }
        let mut names = HashSet::new();
        let mut mappings = HashSet::new();
        let mut pixels = 0u64;
        for glyph in &self.glyphs {
            validate_name(&glyph.name, "glyph name")?;
            if !names.insert(&glyph.name) {
                return Err(format!("duplicate font glyph name '{}'", glyph.name));
            }
            scaled(i64::from(glyph.advance), self.units_per_pixel, "advance")?;
            scaled(i64::from(glyph.bearing_x), self.units_per_pixel, "bearing")?;
            for &codepoint in &glyph.codepoints {
                if char::from_u32(codepoint).is_none() {
                    return Err(format!("invalid Unicode scalar U+{codepoint:04X}"));
                }
                if !mappings.insert(codepoint) {
                    return Err(format!("duplicate Unicode mapping U+{codepoint:04X}"));
                }
                if mappings.len() > MAX_FONT_MAPPINGS {
                    return Err(format!("font exceeds {MAX_FONT_MAPPINGS} Unicode mappings"));
                }
            }
            if let Some([x, y, w, h]) = glyph.rect {
                if w == 0
                    || h == 0
                    || u64::from(x) + u64::from(w) > u64::from(doc.w)
                    || u64::from(y) + u64::from(h) > u64::from(doc.h)
                {
                    return Err(format!(
                        "font glyph '{}' rectangle is empty or outside the atlas",
                        glyph.name
                    ));
                }
                pixels += u64::from(w) * u64::from(h);
                if pixels > MAX_FONT_PIXELS {
                    return Err(format!(
                        "font glyph rectangles exceed {MAX_FONT_PIXELS} source pixels"
                    ));
                }
                // Bound both absolute coordinates and deltas between points.
                scaled(i64::from(w), self.units_per_pixel, "glyph width")?;
                scaled(i64::from(h), self.units_per_pixel, "glyph height")?;
                let right = i64::from(glyph.bearing_x) + i64::from(w);
                scaled(right, self.units_per_pixel, "glyph right edge")?;
                scaled(
                    i64::from(glyph.advance) - right,
                    self.units_per_pixel,
                    "right side bearing",
                )?;
                if i64::from(self.baseline) - i64::from(h) < -i64::from(self.descent) {
                    return Err(format!(
                        "font line metrics do not cover glyph '{}'",
                        glyph.name
                    ));
                }
            }
        }
        Ok(())
    }
}

fn outline(atlas: &RgbaImage, meta: &FontMeta, glyph: &FontGlyph) -> Result<Glyph, String> {
    let Some([atlas_x, atlas_y, width, height]) = glyph.rect else {
        return Ok(Glyph::Empty);
    };
    let unit = i64::from(meta.units_per_pixel);
    let mut contours = Vec::new();
    for y in 0..height {
        let mut x = 0;
        while x < width {
            let alpha = atlas.get_pixel(atlas_x + x, atlas_y + y).0[3];
            if alpha == 0 {
                x += 1;
                continue;
            }
            let start = x;
            while x < width {
                match atlas.get_pixel(atlas_x + x, atlas_y + y).0[3] {
                    0 => break,
                    255 => x += 1,
                    alpha => {
                        return Err(format!(
                            "font glyph '{}' has partial alpha {alpha} at ({}, {}); font export requires transparent or solid pixels",
                            glyph.name,
                            atlas_x + x,
                            atlas_y + y
                        ));
                    }
                }
            }
            if contours.len() >= MAX_GLYPH_RUNS {
                return Err(format!(
                    "font glyph '{}' exceeds the TrueType point limit",
                    glyph.name
                ));
            }
            let left = ((i64::from(glyph.bearing_x) + i64::from(start)) * unit) as i16;
            let right = ((i64::from(glyph.bearing_x) + i64::from(x)) * unit) as i16;
            let top = ((i64::from(meta.baseline) - i64::from(y)) * unit) as i16;
            let bottom = (i64::from(top) - unit) as i16;
            // Clockwise solid rectangles in TrueType's upward Y coordinates.
            // Combining a row's touching cells removes their internal edges.
            contours.push(Contour::from(vec![
                CurvePoint {
                    x: left,
                    y: top,
                    on_curve: true,
                },
                CurvePoint {
                    x: right,
                    y: top,
                    on_curve: true,
                },
                CurvePoint {
                    x: right,
                    y: bottom,
                    on_curve: true,
                },
                CurvePoint {
                    x: left,
                    y: bottom,
                    on_curve: true,
                },
            ]));
        }
    }
    let mut glyph = SimpleGlyph {
        contours,
        ..Default::default()
    };
    glyph.recompute_bounding_box();
    Ok(glyph.into())
}

impl Document {
    /// Replace or clear editable font metadata, validating before mutation.
    pub fn set_font(&mut self, font: Option<FontMeta>) -> Result<(), String> {
        if let Some(font) = &font {
            font.validate(&self.meta)?;
        }
        self.meta.font = font;
        Ok(())
    }

    /// Compile a deterministic static TrueType font from the rendered atlas.
    /// Only fully solid cells become outlines; partially transparent cells fail.
    pub fn font_bytes(&self) -> Result<Vec<u8>, String> {
        self.meta.validate()?;
        let meta = self
            .meta
            .font
            .as_ref()
            .ok_or("document has no font metadata; use doc_font op=set")?;
        meta.validate(&self.meta)?;
        let atlas = self.analysis_image(None, meta.frame)?;
        let order: Vec<usize> = std::iter::once(meta.missing_glyph)
            .chain((0..meta.glyphs.len()).filter(|&index| index != meta.missing_glyph))
            .collect();
        let mut points = 0;
        let mut glyphs = Vec::with_capacity(order.len());
        for &index in &order {
            let glyph = outline(&atlas, meta, &meta.glyphs[index])?;
            if index == meta.missing_glyph && matches!(glyph, Glyph::Empty) {
                return Err("font missing-character glyph must contain solid pixels".into());
            }
            if let Glyph::Simple(simple) = &glyph {
                points += simple.contours.iter().map(Contour::len).sum::<usize>();
            }
            if points > MAX_FONT_POINTS {
                return Err(format!("font exceeds {MAX_FONT_POINTS} outline points"));
            }
            glyphs.push(glyph);
        }
        encode::encode(meta, &order, &glyphs)
    }

    /// Validate and compile before opening the output file.
    pub fn export_font(&self, out: &Path) -> Result<Value, String> {
        let bytes = self.font_bytes()?;
        std::fs::write(out, &bytes).map_err(|e| e.to_string())?;
        let meta = self
            .meta
            .font
            .as_ref()
            .expect("font_bytes validated metadata");
        Ok(
            json!({"path":out.to_string_lossy(), "format":"ttf", "glyphs":meta.glyphs.len(),
            "mappings":meta.glyphs.iter().map(|g|g.codepoints.len()).sum::<usize>(), "bytes":bytes.len(),
            "units_per_em":meta.units_per_em, "units_per_pixel":meta.units_per_pixel}),
        )
    }
}
