# Atelier replay. Rebuild with: atelier replay <this-file>
format = 1
renderer = 1
name = "sc-gpt-6-astra-xhigh-car"
canvas = [32, 32]
frames = [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
palette = ["#1c2334", "#a93240", "#f25b50", "#ffe099", "#3f828e", "#a5e1d8"]
tags = [{ direction = "forward", from = 0, name = "drive", to = 9 }]

[[layers]]
name = "Speed streaks"

[[layers.cels]]
frames = [0]
origin = [7, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
.................112222
.......................
.......................
.......................
.......................
.......................
.......................
.......................
1222...................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.........11222222......
'''

[[layers.cels]]
frames = [1]
origin = [3, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
.................112222
.......................
.......................
.......................
.......................
.......................
.......................
.......................
1222...................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.........11222222......
'''

[[layers.cels]]
frames = [2]
origin = [0, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
................112222
......................
......................
......................
......................
......................
......................
......................
222...................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
........11222222......
'''

[[layers.cels]]
frames = [3]
origin = [4, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
........112222
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
11222222......
'''

[[layers.cels]]
frames = [4]
origin = [0, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
........112222..................
................................
................................
................................
................................
................................
................................
................................
...............................1
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
11222222........................
'''

[[layers.cels]]
frames = [5]
origin = [0, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
....112222.....................
...............................
...............................
...............................
...............................
...............................
...............................
...............................
...........................1222
...............................
...............................
...............................
...............................
...............................
...............................
...............................
...............................
...............................
...............................
...............................
2222...........................
'''

[[layers.cels]]
frames = [6]
origin = [0, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
112222.....................
...........................
...........................
...........................
...........................
...........................
...........................
...........................
.......................1222
'''

[[layers.cels]]
frames = [7]
origin = [0, 8]
legend = { 1 = "#3f828e", 2 = "#a5e1d8" }
grid = '''
11..............................
................................
................................
................................
................................
................................
................................
................................
...................2111.........
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............................2211
'''

[[layers.cels]]
frames = [8]
origin = [15, 16]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
1222.............
.................
.................
.................
.................
.................
.................
.................
.................
.................
.................
.................
.........11222222
'''

[[layers.cels]]
frames = [9]
origin = [11, 8]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
.................1122
.....................
.....................
.....................
.....................
.....................
.....................
.....................
1222.................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.........11222222....
'''

[[layers]]
name = "Exhaust"

[[layers.cels]]
frames = [0]
origin = [3, 21]
legend = { 1 = "#a5e1d8" }
grid = '''
1
'''

[[layers.cels]]
frames = [1]
origin = [1, 20]
legend = { 1 = "#a5e1d8" }
grid = '''
.1
11
'''

[[layers.cels]]
frames = [2]
origin = [0, 19]
legend = { 1 = "#a5e1d8" }
grid = '''
11.
1.1
.11
'''

[[layers.cels]]
frames = [3]
origin = [0, 18]
legend = { 1 = "#a5e1d8", 2 = "#3f828e" }
grid = '''
.1
1.
2.
'''

[[layers.cels]]
frames = [4]
origin = [0, 18]
legend = { 1 = "#3f828e" }
grid = '''
1
'''

[[layers]]
name = "Chassis"

[[layers.cels]]
frames = [0, 1, 4, 5, 6, 9]
origin = [4, 11]
legend = { 1 = "#1c2334", 2 = "#ffe099", 3 = "#f25b50", 4 = "#a5e1d8", 5 = "#3f828e", 6 = "#a93240" }
grid = '''
........11111111..........
.......1222222331.........
......134444144431........
.....13545551545531.......
....1354555514555531......
..1333333333333333332221..
.133333333333622333333322.
.1663333333336333333333221
.1333333333336333333333331
..22666666666666666666662.
151666666666666666666661..
....1111111111111111111...
'''

[[layers.cels]]
frames = [2, 3]
origin = [4, 10]
legend = { 1 = "#1c2334", 2 = "#ffe099", 3 = "#f25b50", 4 = "#a5e1d8", 5 = "#3f828e", 6 = "#a93240" }
grid = '''
........11111111..........
.......1222222331.........
......134444144431........
.....13545551545531.......
....1354555514555531......
..1333333333333333332221..
.133333333333622333333322.
.1663333333336333333333221
.1333333333336333333333331
..22666666666666666666662.
151666666666666666666661..
....1111111111111111111...
'''

[[layers.cels]]
frames = [7, 8]
origin = [4, 12]
legend = { 1 = "#1c2334", 2 = "#ffe099", 3 = "#f25b50", 4 = "#a5e1d8", 5 = "#3f828e", 6 = "#a93240" }
grid = '''
........11111111..........
.......1222222331.........
......134444144431........
.....13545551545531.......
....1354555514555531......
..1333333333333333332221..
.133333333333622333333322.
.1663333333336333333333221
.1333333333336333333333331
..22666666666666666666662.
151666666666666666666661..
....1111111111111111111...
'''

[[layers]]
name = "Rear wheel"

[[layers.cels]]
frames = [0]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#ffe099", 4 = "#a5e1d8" }
grid = '''
..111..
.12321.
1243421
1241421
1222221
.12221.
..111..
'''

[[layers.cels]]
frames = [1]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#ffe099", 4 = "#a5e1d8" }
grid = '''
..111..
.12231.
1244321
1221421
1222421
.12221.
..111..
'''

[[layers.cels]]
frames = [2]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1223341
1221421
1222321
.12221.
..111..
'''

[[layers.cels]]
frames = [3]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1222321
1221421
1223341
.12221.
..111..
'''

[[layers.cels]]
frames = [4]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1222321
1221321
1233421
.12241.
..111..
'''

[[layers.cels]]
frames = [5]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1222221
1231321
1234321
.12421.
..111..
'''

[[layers.cels]]
frames = [6]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1232221
1231221
1243321
.14221.
..111..
'''

[[layers.cels]]
frames = [7]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1232221
1241221
1433221
.12221.
..111..
'''

[[layers.cels]]
frames = [8]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#ffe099", 4 = "#a5e1d8" }
grid = '''
..111..
.12221.
1344221
1231221
1242221
.12221.
..111..
'''

[[layers.cels]]
frames = [9]
origin = [7, 19]
legend = { 1 = "#1c2334", 2 = "#ffe099", 3 = "#3f828e", 4 = "#a5e1d8" }
grid = '''
..111..
.12331.
1324431
1341331
1343331
.13331.
..111..
'''

[[layers]]
name = "Front wheel"

[[layers.cels]]
frames = [0]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#ffe099", 4 = "#a5e1d8" }
grid = '''
..111..
.12321.
1243421
1241421
1222221
.12221.
..111..
'''

[[layers.cels]]
frames = [1]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#ffe099", 4 = "#a5e1d8" }
grid = '''
..111..
.12231.
1244321
1221421
1222421
.12221.
..111..
'''

[[layers.cels]]
frames = [2]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1223341
1221421
1222321
.12221.
..111..
'''

[[layers.cels]]
frames = [3]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1222321
1221421
1223341
.12221.
..111..
'''

[[layers.cels]]
frames = [4]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1222321
1221321
1233421
.12241.
..111..
'''

[[layers.cels]]
frames = [5]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1222221
1231321
1234321
.12421.
..111..
'''

[[layers.cels]]
frames = [6]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1232221
1231221
1243321
.14221.
..111..
'''

[[layers.cels]]
frames = [7]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#a5e1d8", 4 = "#ffe099" }
grid = '''
..111..
.12221.
1232221
1241221
1433221
.12221.
..111..
'''

[[layers.cels]]
frames = [8]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#3f828e", 3 = "#ffe099", 4 = "#a5e1d8" }
grid = '''
..111..
.12221.
1344221
1231221
1242221
.12221.
..111..
'''

[[layers.cels]]
frames = [9]
origin = [21, 19]
legend = { 1 = "#1c2334", 2 = "#ffe099", 3 = "#3f828e", 4 = "#a5e1d8" }
grid = '''
..111..
.12331.
1324431
1341331
1343331
.13331.
..111..
'''
