#!/usr/bin/env python3
"""Render showcase/README.md from showcase/runs.json.

The showcase is a fixed matrix: every model draws the same ten frozen briefs
through atelier's tools, and every GIF is reproducible from the committed
replay beside it. This script only formats that data — it never runs a model.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHOWCASE = ROOT / "showcase"


def main() -> None:
    data = json.loads((SHOWCASE / "runs.json").read_text())
    models = data["models"]
    tasks = data["tasks"]
    by_key = {(run["task"], run["model"]): run for run in data["runs"]}

    out = ["# Showcase", ""]
    out.append("Every model below drew the same ten briefs through atelier's")
    out.append("tools, one agent per task, with no human touching the pixels.")
    out.append("")
    out.append("**Method.** " + data["method"])
    out.append("")
    out.append("**Server.** " + data["server"])
    out.append("")
    out.append("**Verified.** " + data["verified"])
    out.append("")
    out.append("Each GIF is reproducible from the replay beside it:")
    out.append("")
    out.append("```sh")
    out.append("atelier replay showcase/replays/<model>/<task>.jsonl --home /tmp/demo")
    out.append("```")
    out.append("")

    for task in tasks:
        brief = (SHOWCASE / "tasks" / f"{task}.txt").read_text().strip()
        out.append(f"## {task}")
        out.append("")
        out.append("> " + brief.replace("\n", "\n> "))
        out.append("")
        out.append("| " + " | ".join(models) + " |")
        out.append("|" + "---|" * len(models))
        cells = []
        for model in models:
            run = by_key.get((task, model))
            if run is None:
                cells.append("—")
                continue
            cells.append(f'<img src="{run["gif"]}" width="128" alt="{task} by {model}">')
        out.append("| " + " | ".join(cells) + " |")
        stats = []
        for model in models:
            run = by_key.get((task, model))
            if run is None:
                stats.append("—")
                continue
            tokens = f'{run["tokens"]:,}' if run.get("tokens") else "n/a"
            stats.append(f'{run["tool_calls"]} calls<br>{run["looks"]} looks<br>{tokens} tokens')
        out.append("| " + " | ".join(stats) + " |")
        out.append("")

    out.append("---")
    out.append("")
    out.append("Generated by `tools/build-showcase.py` from `showcase/runs.json`.")
    out.append("")
    (SHOWCASE / "README.md").write_text("\n".join(out))
    print(f"wrote {SHOWCASE / 'README.md'}")


if __name__ == "__main__":
    main()
